{% set name = "dask-saturn" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 78af7153a8690ca8761cb092fd01fa95dd48e8b92f8debc6e2817b7fb80578dc

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - distributed
    - pip
    - python
    - requests
  run:
    - distributed
    - python
    - requests

test:
  imports:
    - dask_saturn
  requires:
    - pytest

about:
  home: "https://saturncloud.io/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Dask Cluster objects in Saturn Cloud"
  doc_url: http://docs.saturncloud.io
  dev_url: https://github.com/saturncloud/dask-saturn

extra:
  recipe-maintainers:
    - jsignell
    - forana
    - hhuuggoo
