{% set name = "dask-saturn" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4d00f9e0cbb669c5518c0bfb084bb6a60136342e92de5ee598d231006f8f983c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - distributed
    - pip
    - python
    - requests
  run:
    - distributed
    - python
    - requests

about:
  home: "https://saturncloud.io/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Dask Cluster objects in Saturn Cloud"
  doc_url: http://docs.saturncloud.io
  dev_url: https://github.com/saturncloud/dask-saturn

extra:
  recipe-maintainers:
    - jsignell
    - forana
    - hhuuggoo
