{% set name = "dask-saturn" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: a9f56f3f36f8f1b13f1ff42628717bcc6295f8a131a0293b211829c58e822769

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - distributed ==2.20.0
    - pip
    - python
    - requests
  run:
    - distributed ==2.20.0
    - python
    - requests

about:
  home: "https://saturncloud.io/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Dask Cluster objects in Saturn Cloud"
  doc_url: http://docs.saturncloud.io
  dev_url: https://github.com/saturncloud/dask-saturn

extra:
  recipe-maintainers:
    - jsignell
    - forana
    - hhuuggoo
